### ISSUE TITLE
Wäre es möglich es für auf Chromium Basierte browser zu machen?

### ISSUE THREAD

**Issue by lina-x64** [d43m0nhLInt3r/IServDarkMode#1]
Ich und mein Kumpel arbeiten grade an einer Iserv App für PCs und wir wollten nen dark-mode einbauen (chromium basis)

**Comment by d43m0nhLInt3r** [comment]
Forgive the late reply. You can also integrate the extension directly into your Electron application. Do not forget to adhere to the applicable license. You have to delete the following in manifest.json so that everything works (24-28):     "browser_specific_settings": {
        "gecko": {
          "strict_min_version": "60.0"
        }
      }

**Comment by lina-x64** [comment]
jup we just created a long time ago our own extension for chromium based ones and it worked, but thanks tho!
